[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node dist/boot.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
